//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eLublin.Web.Models.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int id { get; set; }
        public Nullable<System.DateTime> czasDodania { get; set; }
        public string tekst { get; set; }
        public string url { get; set; }
        public string tytul { get; set; }
    }
}
